spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradesign?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  resources:
    static-locations:
    - classpath:/static/ 
mybatis:
  mapper-locations:
  - classpath*:mappers/*.xml
  type-aliases-package: com.hbnu.gradesign.bean