spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456  
    
mybatis:
  mapper-locations:
  - classpath*:mappers/*.xml
  type-aliases-package: com.hbnu.gradesign.bean